### ISSUE TITLE
Anything in terms of wildfly 10 ?

### ISSUE THREAD

**Issue by darrynza** [OpenSCAP/scap-security-guide#1045]
hoping/wondering

**Comment by redhatrises** [comment]
@darrynza can you be more specific?

**Comment by darrynza** [comment]
looking for hardening standards / guide for wildfly 10 os being run CentOS 7

On Fri, Feb 19, 2016 at 12:36 AM, redhatrises <notifications@github.com>
wrote:

> @darrynza <https://github.com/darrynza> can you be more specific?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSCAP/scap-security-guide/issues/1045#issuecomment-185958700>
> .
>



-- 
Darryn Francesco
Mobile: +27780406286
Email: darryn.francesco@gmail.com
Linkdin: http://za.linkedin.com/pub/darryn-francesco/16/531/979

**Comment by iankko** [comment]
@darrynza 
Thank you for checking out.

SSG doesn't provide a SCAP content for WildFly product directly. But we provide content for former [JBossEAP5](https://github.com/OpenSCAP/scap-security-guide/tree/master/JBossEAP5)

The motivation behind this approach is explained here:
&nbsp; &nbsp; [1] http://www.redhat.com/en/technologies/jboss-middleware/community-or-enterprise#

As a temporary workaround it should be possible to use the existing ```JBossEAP5``` content to scan WildFly instance(s) too. We are aware though the ```JBossEAP5``` content is:
* currently provided in monolithic form preventing updates / enhancements:
  https://github.com/OpenSCAP/scap-security-guide/issues/1046
* and outdated (missing support for v6 and v7 Beta of the JBossEAP product):
  https://github.com/OpenSCAP/scap-security-guide/issues/1047

For now I have filed those two aforementioned tickets, to get the current situation changed. Thank you for your patience till the updated content is available. (Till that moment existing content for ```JBossEAP5``` can be used instead since:
* it already provides basic security controls detailing which security areas should be checked when inspecting sanity of configuration of JBossEAP / WildFly server,
* it more than likely the SCAP content for JBossEAP 6 / JBossEAP 7 will inherit the existing JBossEAP 5 content and add new security controls for features introduced in these newer JBossEAP versions on top of that.)

Hope this being helpful.

Regards, Jan.

**Comment by mpreisler** [comment]
No response from OP.
