### ISSUE TITLE
OVAL 5.11 constructs rejected by contemporary RHEL6 OpenSCAP

### ISSUE THREAD

**Issue by GaryGapinski** [OpenSCAP/scap-security-guide#1064]
shared/oval/oval_5.11/rsyslog_files_groupownership.xml
shared/oval/oval_5.11/rsyslog_files_ownership.xml
shared/oval/oval_5.11/rsyslog_files_permissions.xml

all cause schema validation errors with OpenSCAP v1.0.10, which is the contemporary version of OpenSCAP provided on RHEL6. Such constructs should be limited to platforms on which OVAL 5.11 support is provided.

This was based on the master branch. Should I have been tracking a different version in order to ensure related platform support by OpenSCAP?

**Comment by isimluk** [comment]
@GaryGapinski you are right. But I see this as a wontfix, if not cantfix. Let me explain how we come into this situation.

Scap-security-guide is an upstream project. SCAP-Security-Guide tries to be usable on any platform. However, the main goal of the project as I see it, is to develop next generation policies. In this case, I think we should not hinder development of new checks just because some of the target platforms cannot parse it at the moment. We want to synchronize delivery of scanner capabilities and policy checks as close as possible. After all, it has been years since we proposed this feature for rsyslog configs to OVAL board.


On top of that, I think there is some mechanism in SSG build scripts to detect openscap capabilities. So, if you are building SSG on RHEL-6 with older OpenSCAP, OVAL-5.11 checks are not included.

Please rebuild RHEL-6 directory with older OpenSCAP.

**Comment by iankko** [comment]
> On top of that, I think there is some mechanism in SSG build scripts to detect openscap capabilities. So, if you are building SSG on RHEL-6 with older OpenSCAP, OVAL-5.11 checks are not included.

That's correct. Those ```rsyslog``` OVAL checks won't be included on RHEL-6 when building with openscap-1.0.X (SSG build system detects and ensures it).

Agree with the above statement.  There's even possible at some point in the future the RHEL-6 content will be based on OVAL-5.11 language version.

Hope this helps. Jan
