### ISSUE TITLE
RHEL6 libreswan vs openswan

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1260]
In the latest STIGS for RHEL 6 one of the rules is that openswan must be installed, however in 6.8 when you try to install openswan you get the message in the yum log that libreswan has replaced openswan and thus my machine keeps failing that part of the SCAP scan for checking if openswan is installed even though libreswan is installed. 

Thanks to Jason R. for the bug report.

**Comment by iankko** [comment]
Hi Shawn,
  can you clarify the version of scap-security-guide this failing report about openswan not being installed has been retrieved from? Asking because the ````RHEL/6``` ```package_openswan_installed``` OVAL check has been already enhanced to count with this situation:
 * https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/6/input/oval/package_openswan_installed.xml

That version should properly dealt with both openswan / libreswan packages being installed on RHEL-6.8 system.

**Comment by shawndwells** [comment]
Thanks @iankko! This was brought up on the gov-sec mailing list, so created a ticket to track it. Closing ticket -- this is shipping in RHEL6 now.
