### ISSUE TITLE
RHEL7 SSG doesn't ship HTML guides or HTML tables

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1297]
# rpm -ql scap-security-guide
/usr/share/doc/scap-security-guide-0.1.25
/usr/share/doc/scap-security-guide-0.1.25/DISCLAIMER
/usr/share/doc/scap-security-guide-0.1.25/LICENSE
/usr/share/doc/scap-security-guide-0.1.25/table-rhel6-cces.html
/usr/share/doc/scap-security-guide-0.1.25/table-rhel6-nistrefs-common.html
/usr/share/doc/scap-security-guide-0.1.25/table-rhel6-nistrefs.html
/usr/share/doc/scap-security-guide-0.1.25/table-rhel6-srgmap-flat.html
/usr/share/doc/scap-security-guide-0.1.25/table-rhel6-srgmap-flat.xhtml
/usr/share/doc/scap-security-guide-0.1.25/table-rhel6-srgmap.html
/usr/share/doc/scap-security-guide-0.1.25/table-rhel6-stig.html
/usr/share/doc/scap-security-guide-0.1.25/table-rhel7-cces.html
/usr/share/man/en/man8/scap-security-guide.8.gz
/usr/share/scap-security-guide
/usr/share/scap-security-guide/kickstart
/usr/share/scap-security-guide/kickstart/ssg-rhel6-stig-ks.cfg
/usr/share/scap-security-guide/kickstart/ssg-rhel6-usgcb-server-with-gui-ks.cfg
/usr/share/scap-security-guide/kickstart/ssg-rhel7-pci-dss-server-with-gui-oaa-ks.cfg
/usr/share/scap-security-guide/remediation_functions
/usr/share/xml/scap
/usr/share/xml/scap/ssg
/usr/share/xml/scap/ssg/content
/usr/share/xml/scap/ssg/content/ssg-firefox-ds.xml
/usr/share/xml/scap/ssg/content/ssg-jre-ds.xml
/usr/share/xml/scap/ssg/content/ssg-rhel6-ds.xml
/usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-dictionary.xml
/usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-oval.xml
/usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
/usr/share/xml/scap/ssg/content/ssg-rhel7-oval.xml
/usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml

**Comment by iankko** [comment]
@shawndwells 
As for the HTML guides they are available in separate ```scap-security-guide-doc``` subpackage (one HTML  guide file for every profile available). They have been moved to ```-doc``` subpackage, because they are too space demanding (usage of ```/usr/share/doc/scap-security-guide-0.1.30/guides``` shows 71 MB). Since scap-security-guide is also required for other products (e.g. Spacewalk uses it via spacewalk-oscap RPM to scan the client), we can't allow base scap-security-guide RPM to be such big.

As for HTML tables and kickstart files, have created:
* https://github.com/OpenSCAP/scap-security-guide/pull/1315

which should fix the issue(s).

Review appreciated.
