### ISSUE TITLE
Need more CCEs

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1607]
We're down to our last few CCEs.

Sent a note today (8-DEC) to NIST requesting more.

**Comment by konstruktoid** [comment]
Does this also include CCEs for e.g Debian and Centos, or how does that work?

**Comment by redhatrises** [comment]
> Does this also include CCEs for e.g Debian and Centos, or how does that work?

No, the CCEs are specific to RHEL products because once a CCE is applied to an XCCDF rule, it becomes binding that Red Hat, Inc. has to attest to that rule which may not be accurate for Debian. Also, CCEs typically are assigned to OS vendors that go through the certification processes. which in this case, CentOS has not.

**Comment by konstruktoid** [comment]
Thank alot @redhatrises for clarifying.

**Comment by shawndwells** [comment]
Happy to make intros between the NIST CCE people and other vendors though.

**Comment by shawndwells** [comment]
14dec2016: still waiting to hear back from NIST. Pinged them again tonight.

**Comment by shawndwells** [comment]
16dec2016: NIST replied, they're getting us new CCEs. I asked for ~750. Sounds large, but we'll likely need 250 to cover docker/OpenShift, around 400 for OpenStack, and another 100 for RHEL. CCEs are a shared pool so we can use as needed.... those #s are rough estimates.

Should have within next few days.

**Comment by shawndwells** [comment]
19dec: CCEs received from NIST. PR https://github.com/OpenSCAP/scap-security-guide/issues/1617 submitted to merge them into general pool.
