### ISSUE TITLE
Kernel FIPS 140-2 Mode (fips=1 kernel flag) should be Optional

### ISSUE THREAD

**Issue by fcaviggia** [OpenSCAP/scap-security-guide#1609]
Forcing the kernel into FIPS only mode will break a lot of software (including IdM, sssd, and other packages) that use md5 internally - while the goal would be to have everything work with FIPS enabled - the current requirement is to allow FIPS 140-2 for services and connections like HTTPS, SSHD, and kerberos. Forcing this in scap-security-guide-0.1.31 can cause undesired issues on the system.

**Comment by trevor-vaughan** [comment]
Since I seem to be running around digging up old threads about FIPS 140-2 recently, I thought that I would come weigh in here as well.

If a subsystem is not using proper FIPS validated cryptography, then that system is not FISMA compliant.

This requirement cannot be waived per FIPS 200.

Undesired operation of the system indicates a failure on the part of the software, not the system. For Red Hat systems, the kernel needs to be loaded into FIPS mode. For Java (per November 2016) they need to be using the FIPS BouncyCastle or link natively to GNU-TLS or OpenSSL (somehow). Anything in Golang is toast unless it's hooking to the system OpenSSL and anything dragging along it's own stack of stuff is probably completely hosed (I'm looking at you containers).

FIPS 140-3 might make things better but it has t 1) come out and 2) get adopted and, until then, FISMA says FIPS 140-2.

**Comment by shawndwells** [comment]
Didn't realize this was still open. Agree with @trevor-vaughan ... even if it awkwardly breaks other RHT tech, such things should be reported as bugs.

**Comment by fcaviggia** [comment]
This was the big stumbling block for me...

https://www.freeipa.org/page/V4/FreeIPA-on-FIPS

**Comment by trevor-vaughan** [comment]
I would like to note that there should be some text about needing to kickstart your system in FIPS mode. We're finding that trying to flip your system back and forth (unless it's just a reboot) is bad news. We ended up with SSH private keys that couldn't be used and a whole host of other issues due to key generation and hash selection when the system was not in FIPS mode.

Turning it *off* is fine, but you want to make sure it's on when the system is initializing and you're installing new apps and getting them running.

**Comment by fcaviggia** [comment]
@shawndwells, you do realize that this might hurt some of the current deployment efforts for OpenShift due to the Go Language (Kubernetes) if the products aren't FISMA compliant? It will at least be a POA&M against the deployment.

Also, it looks like the FreeIPA fixed the FIPS 140-2 issues with FreeIPA 4.5.0, which is hopefully coming with RHEL 7.4 release:

https://www.freeipa.org/page/Releases/4.5.0#FIPS_140-2_Support
https://bugzilla.redhat.com/show_bug.cgi?id=1392858

**Comment by trevor-vaughan** [comment]
@fcaviggia If they don't comply, they don't comply and need to be fixed. Identifying issues happens quite often when the laws start getting enforced.

**Comment by shawndwells** [comment]
On 5/24/17 11:27 AM, Frank Caviggia wrote:
> @shawndwells <https://github.com/shawndwells>, you do realize that
> this might hurt some of the current deployment efforts for OpenShift
> due to the Go Language (Kubernetes) if the products aren't FISMA
> compliant? It will at least be a POA&M against the deployment.
Acutely aware. It's an unenviable position, being a Red Hatter and
recommending baselines *knowing for certain* some Red Hat products will
break. But like Trevor said... if products break, such issues should be
treated as bugs by the software vendor.

Ultimately, it's *law* that federal systems use FIPS. We see enforcement
by US Gov in formal baselines like DoD STIG, FISMA, and USGCB. RHEL must
be configured in accordance with that.

For customers who have FIPS waivers, or for non-gov information systems,
alternative SCAP profiles are provided (e.g. PCI, Commercial Cloud, etc).

**Comment by trevor-vaughan** [comment]
@shawndwells Waivers you say?! Check out Section 11 of http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.200.pdf.

It gets more heavy handed in other documents, but that's the fun one.

**Comment by shawndwells** [comment]
On 5/24/17 4:29 PM, Trevor Vaughan wrote:
>
> @shawndwells <https://github.com/shawndwells> Waivers you say?! Check
> out Section 11 of http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.200.pdf.
>
> It gets more heavy handed in other documents, but that's the fun one.
>

Shhhh. Don't tell the ISSMs that they don't have the authority to waive
FIPS. Especially on federal systems like cloud.gov.

**Comment by trevor-vaughan** [comment]
This has been the best conversation ever....
