### ISSUE TITLE
needs remediation: xccdf_org.ssgproject.content_rule_sshd_use_approved_macs

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#1889]

**Comment by jan-cerny** [comment]
We already have a remediation for `sshd_use_approved_macs`.
(it is in https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/templates/static/bash/sshd_use_approved_macs.sh )

Perhpaps you mean `sshd_use_approved_ciphers`? We don't have a remediation for that.

**Comment by shawndwells** [comment]
After applying remediation the rule still fails -- so either an OVAL false positive or remediation is broke. Haven't explored which case is happening yet. Appreciate any help!

**Comment by jan-cerny** [comment]
@shawndwells I have found that the OVAL for RHEL 7 requires exactly those MACs: 
`hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-sha1-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com`
The regex used in OVAL is not good, because it requires the MACs listed exactly in the given order, which can cause bugs like this: https://bugzilla.redhat.com/show_bug.cgi?id=1413494
Morevoer the remediation is in `shared` directory and have only these:
`hmac-sha2-512,hmac-sha2-256,hmac-sha1`

I think that we need to change both OVAL and remediation script. I will provide a pull request fixing those.

**Comment by jan-cerny** [comment]
https://github.com/OpenSCAP/scap-security-guide/pull/1908

**Comment by shawndwells** [comment]
On 4/6/17 5:24 AM, Jan Černý wrote:
> I think that we need to change both OVAL and remediation script. I
> will provide a pull request fixing those.

You're *totally* right. That technical debt has long been on the list to
fix. Would be great to cross it off.
