### ISSUE TITLE
xccdf_org.ssgproject.content_rule_disable_prelink fails on CentOS

### ISSUE THREAD

**Issue by gregdurham** [OpenSCAP/scap-security-guide#1902]
Running the disa stigs against CentOS 7, we are running into a false positive I believe due to the version not matching.

https://github.com/OpenSCAP/scap-security-guide/blob/d0af7b820664fe193195eebe498840b654bdf509/shared/oval/disable_prelink.xml#L26

Should this include CentOS 7 in the list of 'not installed'?

**Comment by shawndwells** [comment]
RPM versions should align between RHEL and its derivatives. If you're using the CentOS content, the build system strips RHEL-specific tags (like platform identifiers), so that shouldn't be a problem.

Can you attach the related parts of an OVAL results file? Would give us the exact test that causes this rule to pass -- and we can compare that with what's on the system.

**Comment by rchayes** [comment]
I believe it's the installed_OS check that's causing false test to fail not rpm.

        <criteria operator="OR" comment="System is RHEL7 or Fedora">
          <extend_definition comment="Installed OS is RHEL7" definition_ref="installed_OS_is_rhel7" />
          <extend_definition comment="Installed OS is Fedora" definition_ref="installed_OS_is_fedora" />
        </criteria>

oval:ssg-package_prelink_removed:def:1 true compliance 
[package_prelink_removed] Package prelink Removed

**Comment by gregdurham** [comment]
Thanks @rchayes, sorry I lost track of this ticket, that is correct.

**Comment by pysysops** [comment]
I'm seeing this too. are there any workarounds for it?

**Comment by pysysops** [comment]
Also FWIW: I get another failure too:
```
aws:        Disable Prelinking
aws:        xccdf_org.ssgproject.content_rule_disable_prelink
aws: Ident
aws:
aws:        error
aws:
aws:        Ensure auditd Collects Information on the Use of Privileged Commands
aws:        xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands
aws: Ident
aws:
aws:        error
```

I haven't dug too deep into it at the moment. Basically I'm applying the pci-dss profile to a base AMI I want to secure and have evidence of from inception and the oscap toolset is perfect for that 😸

**Comment by pysysops** [comment]
Okay.... There is a problem with a line of code: https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/7/templates/static/bash/disable_prelink.sh#L16

we use the command: `/usr/sbin/prelink -ua` assuming that it is installed. On a CentOS 7 server with prelink removed it causes remediation to fail. I know this is probably due to whatever is trying to detect the presence of prelink giving a false positive but perhaps it would be better to test that the file is executable / exists first a la `[ -x /usr/sbin/prelink ] && /usr/sbin/prelink -ua` this would at least stop the error from occurring on remediation. 

I'll track back through the code to see how / where it tries (and fails) to detect that prelink isn't on a system...

For now, I've just added the prelink package at kickstart time to get it to pass remediation but it's not ideal.
