### ISSUE TITLE
Test 'oval:ssg-test_multi_user_wants_pcscd.socket:tst:1' evaluated as false

### ISSUE THREAD

**Issue by phani-achanta** [OpenSCAP/scap-security-guide#2157]
Debug loggin oscap shows that pcscd.socket exists as dependency .
However the test fails 

> D: oscap: ("seap.msg" ":id" 1 ":reply-id" 1 (2 () ((("systemdunitdependency_item" ":id" "1279561" ) ("unit" "multi-user.target" ) ("dependency" "basic.target" ) ("dependency" "sysinit.target" ) ("dependency" "systemd-journal-flush.service" ) 
> ....
> ("dependency" "pcscd.socket" ) 
> ....
> ) ) () ) ) [oscap(27674):oscap(7fdacac86840):seap-packet.c:903:SEAP_packet_recv]

**Comment by sradigan** [comment]
This is still an issue in 0.1.35 and master.

This rule fails due to the oval:ssg-state_systemd_pcscd.socket_on:ste:1 check failing.

The issue is that the templating is appending ".service" to every service listed in the csv.

Link to csv with pcscd.socket entry [here](https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/7/templates/csv/oval_5.11/services_enabled.csv#L13)

Template containing hard ".service" substitution [here](https://github.com/OpenSCAP/scap-security-guide/blob/460c629c7160b0c5c367e5d56b8e4b35754b66f3/RHEL/7/templates/oval_5.11_templates/template_OVAL_service_enabled#L28)

Link to regex replace [here](https://github.com/OpenSCAP/scap-security-guide/blob/460c629c7160b0c5c367e5d56b8e4b35754b66f3/shared/templates/create_services_enabled.py#L43)

I'd love to edit the code and make a PR, but I don't really know what the best way of handling these cases would be. Maybe preprocessing the csv entry looking for other [common systemd unit postfixes](https://www.freedesktop.org/software/systemd/man/systemd.unit.html)?

**Comment by sradigan** [comment]
This certainly did fix the issue, but I think it broke the other services as the oval check content is looking for <entry in csv>.service for many of them. I'll try to get some possible fixes in here soon. I wanted to let you know that the fix broke some other service checks such as ntp and automounter.
