### ISSUE TITLE
Yum check for updates gets error

### ISSUE THREAD

**Issue by MollyJoBault** [OpenSCAP/scap-security-guide#2197]
Ran remediation on xccdf_org.ssgproject.content_rule_security_patches_up_to_date and I got it back as "Not checked" with the following error.  There seems to be a bash remediation script for it, I don't understand why it is not running.

`None of the check-content-ref elements was resolvable.`

**Comment by redhatrises** [comment]
I am assuming that this is with CentOS? If so, what additional SCAP content are you running that contains CVE checks?

**Comment by MollyJoBault** [comment]
Yes, you are correct, this is with CentOS 7.3.  This is the only one that uses "https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2".  

<rule-result idref="xccdf_org.ssgproject.content_rule_security_patches_up_to_date" time="2017-07-31T11:20:49" severity="high" weight="1.000000">
      <result>notchecked</result>
      <message severity="info">None of the check-content-ref elements was resolvable.</message>
      <check system="http://oval.mitre.org/XMLSchema/oval-definitions-5">
        <check-content-ref href="https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2"/>
      </check>
    </rule-result>

**Comment by redhatrises** [comment]
So... this will always error and never work as the CVE content for CentOS does not apply.

**Comment by MollyJoBault** [comment]
Shouldn't yum update work though?  :)  Sounds like we need a new check for CentOS systems.

**Comment by MollyJoBault** [comment]
@redhatrises is there a script somewhere that checks for missing ssg content?  Like no remediation script?

**Comment by mpreisler** [comment]
@MollyJoBault check out `profile-stats.py` in the SSG repo. It can output check and fix coverage for all our content.

**Comment by redhatrises** [comment]
Unfortunately, this check will always fail or come back as "not applicable" on CentOS systems. This is because there is no vulnerability OVAL feed for the XCCDF to reference. Therefore, the remediation will also not apply because the check is not applicable to CentOS.

**Comment by steveh138** [comment]
I would like to see if this can be reopened. I use Foreman and I am able to get errata from CentOS repos. Also EPEL posts errata as well. This would be great to include in my SCAP reports.

**Comment by redhatrises** [comment]
@steveh138 can you provide links to the errata? It is important to note that this check pulls down CVE OVAL files which both EPEL and CentOS do not have. The reason the remediation script fail is because the CVE OVAL is never run as the CVE OVAL file is downloaded from RHT. Also, unfortunately as of now, there is no way to tailor this type of check.

**Comment by steveh138** [comment]
Here is a link to the project that pulls them in. Once they're in Foreman all the information is available via repositories and content view provided by Katello.

https://github.com/rdrgmnzs/pulp_centos_errata_import

**Comment by steveh138** [comment]
These are the two sources for the OVAL info

http://cefs.steve-meier.de/errata.latest.xml
https://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml

**Comment by redhatrises** [comment]
Thanks @steveh138.

OpenSCAP has zero ability to read and digest RPM repository XML errata in the form of http://cefs.steve-meier.de/errata.latest.xml as this repository XML is based on RPM repo data and not OVAL XML standards.In addition, the OVAL content at https://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml is for Red Hat only and does not truly apply to CentOS. For the request in this ticket to actually be implemented, a few things have to happen on the CentOS side first such as:

- Security QE/QA and security CVE attestation for patches and bug fixes.
- Valid OVAL content published and regularly maintained by CentOS at a CentOS url.
- The XCCDF standard needs to be evolved to handle different urls for `<content-check-ref />` or some sort of code to implement the new url in the build system. 

Finally because `<content-check-ref />` is not applicable to CentOS, the remediation scripts will never be run or executed.

**Comment by steveh138** [comment]
TY for the explanation
