### ISSUE TITLE
Rule RHEL-07-010320 not consistent with STIG

### ISSUE THREAD

**Issue by mrabe142** [OpenSCAP/scap-security-guide#2624]
#### Description of problem:
I am running an OpenSCAP scan with the SSG DISA STIG profile.

The description from the OpenSCAP scan results states that the following sould be in the **/etc/pam.d/system-auth** and **/etc/pam.d/password-auth** files:
```
auth required pam_faillock.so preauth silent deny=3 unlock_time=never fail_interval=900
auth [default=die] pam_faillock.so authfail deny=3 unlock_time=never fail_interval=900
account required pam_faillock.so
```

According to the lastest version of the STIG (Jan 28 2018), the following should be in those files according to RHEL-07-010320:
```
auth required pam_faillock.so preauth silent audit deny=3 even_deny_root fail_interval=900 unlock_time=604800
auth sufficient pam_unix.so try_first_pass
auth [default=die] pam_faillock.so authfail audit deny=3 even_deny_root fail_interval=900 unlock_time=604800
account required pam_faillock.so
```

#### SCAP Security Guide Version:
SSG 0.1.37-1

#### Operating System Version:
RHEL 7.4

#### Steps to Reproduce:

1. Verify contents of files match what is expected of the STIG
2. Run OpenSCAP scan
3. Generate HTML report and look over results

#### Actual Results:
Failed test during scan

#### Expected Results:
Passed test during scan

**Comment by redhatrises** [comment]
@mrabe142 this is requirement is in `RHEL-07-010330` and not `RHEL-07-010320` which is selected in the `stig-rhel7-disa` profile.

**Comment by mrabe142** [comment]
Looking at RHEL-07-010330, it has the same fix text as 010320.

This is the fix text for 010330 as of the latest version of the STIG:
```
auth required pam_faillock.so preauth silent audit deny=3 even_deny_root fail_interval=900 unlock_time=604800
auth sufficient pam_unix.so try_first_pass
auth [default=die] pam_faillock.so authfail audit deny=3 even_deny_root fail_interval=900 unlock_time=604800
account required pam_faillock.so
```

**Comment by redhatrises** [comment]
Okay. So looking at this, adding `even_deny_root` should stay in `RHEL-07-010330` and not be added to `RHEL-07-010320`. This is a copy/paste bug in the source content, and I am not sure that the `pam_unix.so` line needs to be added unless it is helpful to know where the first `pam_faillock.so` line should go?

**Comment by mrabe142** [comment]
Depending on how you interpret the wording of each rule, the fix content could be the same for both of them .  `010320` is not specific as to which accounts should be locked (it is vague enough this could include root as well) and `010330` applies specifically to root.  The second rule is almost redundant since the first rule could cover all accounts.

I am not sure about the `pam_unix.so` line.  It is included in the fix text for both of them but not in either of the check content sections.

**Comment by redhatrises** [comment]
> Depending on how you interpret the wording of each rule, the fix content could be the same for both of them .  `010320` is not specific as to which accounts should be locked (it is vague enough this could include root as well) and `010330` applies specifically to root.  The second rule is almost redundant since the first rule could cover all accounts.

This is by design that `even_deny_root` is not in `010320` but is in `010330`. `even_deny_root` is second configuration item and should only be referenced in a second rule. Rules that perform multiple configurations are always requested to be broken out as this one was from the beginning (whether they all are or not is a different story). This not only allows content to be more customizable, but it also handles all the STIG customers who do not configure `even_deny_root`. As more users and different compliance entities use the same content, having `even_deny_root` in `010320` as well is not only confusing, but considered by them as a bug. The official content of `010320` should also reflect this.
A ticket should be opened with DISA to remove `even_deny_root` from `010320` as it exists in `010330`.

**Comment by shawndwells** [comment]
``RHEL-07-010320`` has the following check text:
`````
If the "unlock_time" setting is greater than "604800" on both lines with the "pam_faillock.so" module name or is missing from a line, this is a finding
`````

That rule should map to ``accounts_passwords_pam_faillock_unlock_time.rule`` (which it does). In exploring this issue there were some mapping issues found -- those are tracked under https://github.com/OpenSCAP/scap-security-guide/issues/2729

Because the SSG rule appropriately evaluates the DISA STIG check-text, this ticket can be closed.
