### ISSUE TITLE
[RHEL7] disable_ctrlaltdel_reboot update for systemd

### ISSUE THREAD

**Issue by neo-aeon** [OpenSCAP/scap-security-guide#293]
systemd has done away with */etc/init/control-alt-delete.conf* and replaced it with a *ctrl-alt-del.target*.

The system default in */usr/lib/systemd/system* is a logical link to *reboot.target*.

Superseding the system default in */etc/systemd/system* is fairly easy, detecting it isn't.

Proposed remediation:
`mkdir /etc/systemd/system/ctrl-alt-del.target.wants; echo -e "[Unit]\nDescription=Log CtrlAltDel\n\n[Service]\nExecStart=/bin/logger -p security.info Control-Alt-Delete pressed" > /etc/systemd/system/ctrl-alt-del.target.wants/ctrl-alt-del.service;  echo -e "[Unit]\nDescription=Log CtrlAltDel" > /etc/systemd/system/ctrl-alt-del.target; chmod 0644 /etc/systemd/system/ctrl-alt-del.target /etc/systemd/system/ctrl-alt-del.target.wants/ctrl-alt-del.service ; chmod 0755 /etc/systemd/system/ctrl-alt-del.target.wants; systemctl daemon-reload`

Breaking this down:
create a new ctrl-alt-del.target.wants directory with a simple ctrl-alt-del.service in it.

The simple service runs the logger -p we're used to.

The chmods fix the perms due to umask 077.

systemctl daemon-reload makes the target active.

Testing ctrl-alt-del at a virtual terminal proves the syslog is written.

Proposed evaluation:
`if [ -d /etc/systemd/system/ctrl-alt-del.target.wants ]; then grep logger /etc/systemd/system/ctrl-alt-del.target.wants/ctrl-alt-del.service; fi`

should return:
ExecStart=/bin/logger -p security.info Control-Alt-Delete pressed

I can't figure out a way to test for the presence of the special unit files with systemctl.  So it has to be brute forced.

http://www.freedesktop.org/software/systemd/man/systemd.special.html

**Comment by Tricky-Dicky** [comment]
I found this really useful as I too needed to prevent ctrl+alt+del from actually issuing a reboot and instead do something else ... using the code supplied by @neo-aeon above to create the service I managed to inhibit ctrl+alt+del and do the 'other action' but it only works once (per boot) because the ctrl-alt-del.target is considered active after the first attempt because the service runs.
The fix for this is to use ctrl-alt-del.target.**requires** instead of ctrl-alt-del.target.wants for the location of the ctrl-alt-del.service script and use a Type=oneshot

Sorry to add this to a closed issue but this is the only place I have found where this info is available and big thanks to @neo-aeon for coming up with the method in the first place.
