### ISSUE TITLE
Ubuntu Support in OpenSCAP

### ISSUE THREAD

**Issue by openprivacy** [OpenSCAP/scap-security-guide#537]
I'm considering deploying a system on the Ubuntu OS (various reasons). I understand the only certified STIG is for RHEL6 (which may be my final choice) but am wondering if anyone here has some feedback on the following:
- while Ubuntu has SELinux in the (Debian) kernel, it's default MAC implementation is AppArmor which seems simpler and easier to audit than SELinux. While SELinux is more fine-grained, are there any major reasons why AppArmor should not be used?
- if I go the Ubuntu route, are contributions of SCAP content for Ubuntu welcome?
- is anyone else working on Ubuntu SCAP content?

**Comment by shawndwells** [comment]
On 4/29/15 11:57 AM, openprivacy wrote:
>
> I'm considering deploying a system on the Ubuntu OS (various reasons). 
> I understand the only certified STIG is for RHEL6 (which may be my 
> final choice) but am wondering if anyone here has some feedback on the 
> following:
>
>   * while Ubuntu has SELinux in the (Debian) kernel, it's default MAC
>     implementation is AppArmor which seems simpler and easier to audit
>     than SELinux. While SELinux is more fine-grained, are there any
>     major reasons why AppArmor should not be used?
>

gov-sec@redhat.com is a better place for this question 
(http://www.redhat.com/mailman/listinfo/gov-sec). That list contains 
linux users in the government space who can comment on their decision 
factors.

>   * if I go the Ubuntu route, are contributions of SCAP content for
>     Ubuntu welcome?
>
Because we're an upstream community, largely of volunteers, community 
matters the most. If enough interested parties are interested in 
developing (and maintaining!) Ubuntu content then it makes perfect 
sense. If the content would linger and quickly become stagnant, not so much.

>   * is anyone else working on Ubuntu SCAP content?
>
/me points to Greg Elin and Dave Smith

**Comment by openprivacy** [comment]
Thanks for the reply!
