### ISSUE TITLE
Remediation for RHEL7 service_chronyd_or_ntpd_enabled

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/scap-security-guide#742]

**Comment by redhatrises** [comment]
I think that we could do the following for this one:

- If chronyd is installed but not ntpd, enable chronyd
- If ntpd is installed but not chrond, enable ntpd

If both ntpd and chronyd are installed, I don't think that we can remediate this as we don't know the organizational layout. @shawndwells @iankko Thoughts? Agree?

**Comment by iankko** [comment]
@redhatrises 
> I think that we could do the following for this one:

    If chronyd is installed but not ntpd, enable chronyd
    If ntpd is installed but not chrond, enable ntpd
> If both ntpd and chronyd are installed, I don't think that we can remediate this as we don't know the organizational layout. @shawndwells @iankko Thoughts? Agree?

The above approach when just one of the rpms is installed => enable that corresponding services looks reasonable to me. For the cases:
* neither of ```chrony``` or ```ntp``` is installed  -- I would suggest to the script to install ```chrony``` and enabled ```chronyd``` service by default (since this is what RHEL-7 is actually doing in the default configuration),
* both of ```chrony``` and ```ntp``` packages are installed -- I would suggest to enable ```chronyd``` service (this again being the default approach for RHEL-7).

From my experience ```ntpd``` is enabled (```ntp``` installed, and ```ntpd``` enabled only in case the organization would desire some additional feature / product installed on the system:
* e.g. for FreeIPA case [ipa-server-install will disable chronyd in favour of ntpd](http://www.unixmen.com/configure-freeipa-server-centos-7/), or 
* e.g. OpenStack installation also requires ```ntpd``` [to be configured](http://docs.openstack.org/icehouse/install-guide/install/yum/content/basics-ntp.html) rather than ```chronyd```.

Based on the above the usecase ```ntpd``` to be enabled in rather than ```chronyd``` would be present only on "more complex" environment installations (where some other product is installed on top of RHEL-7 product) or in cases when the organization would require some NTP protocol feature not implemented in ```chronyd``` yet (and therefore ```ntpd``` would be preferred daemon in this case). But in both of these cases I assume the system administrators of those systems would be familiar with the environment enough to handle the ```ntpd``` service enablement on their own resources. IMHO the provided remediation script just need to properly handle the basic / default use case scenario (since attempt to detect e.g. if FreeIPA isn't installed or if OpenStack isn't installed on the particular system wouldn't be trivial task to do within that remediation script). And I don't think this detection of these complex environments is truly necessary.
