### ISSUE TITLE
[BugFix] [RHEL/7] [Fedora] Revisit OVAL & remediation for 'disable_interactive_boot' rule to properly handle also 'systemd.confirm_spawn=1' case kernel boot argument

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#851]
Per:
&nbsp; &nbsp; [1] https://github.com/OpenSCAP/scap-security-guide/issues/823

and 
&nbsp; &nbsp; [2] https://access.redhat.com/solutions/25950

besides of setting ```PROMPT=yes``` in ```/etc/sysconfig/init``` configuration file, there's also another way how the user can enable interactive boot to happen (adding 'confirm' kernel boot argument to the kernel command line for RHEL-6 system. This latter case is covered by [1] for the case of RHEL-6 system).

But for ```systemd``` based products (RHEL-7 and Fedora) there also (besides configuring ```/etc/sysconfig/init```) is a way how to configure / enforce interactive service startup at kernel boot -- namely the ```systemd.confirm_spawn=1``` option being provided on the kernel command line:
&nbsp; &nbsp; [3] https://rhsummit.files.wordpress.com/2014/04/summit_demystifying_systemd1.pdf
 (Page #20 of that presentation)

Therefore the current OVAL check & remediations (if exist) for RHEL-7 and Fedora for ```disable_interactive_boot``` rule should be revisited to:
* see if configuring ```PROMPT=no```option  in ```/etc/sysconfig/init``` file still works also for ```systemd``` based products,
* the existing RHEL-7 and Fedora XCCDF & OVAL for this rule should be enhanced to properly handle also the case the ```systemd.confirm_spawn=1``` setting has been provided on the kernel command line.

**Comment by isimluk** [comment]
@iankko, I see the #852 has been merged. Can we close this issue, or is there anything else that remains to be done?

**Comment by kazens** [comment]
@isimluk  Sorry if I'm missing something, but I don't see the changes merged for RHEL7:

https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/oval/disable_interactive_boot.xml
https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/7/input/xccdf/system/accounts/physical.xml

RHEL7/systemd does not follow the  `PROMPT=no` option in /etc/sysconfig/init, so that test should be removed.
RHEL7/systemd uses `systemd.confirm_spawn=1` on the kernel command line to do an interactive boot, that test needs to be added.

**Comment by iankko** [comment]
Correct. The fix for this change needs to be implemented yet. Pls keep the issue opened.

**Comment by isimluk** [comment]
Ah. Understood. Thank You!
